import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import {
  cloudflared,
  credentialsPathForTunnel,
  ensureCloudflared,
  ensureCloudflaredCert,
  listTunnels,
  spawnCloudflared,
} from "../../scripts/lib/cloudflared.ts";
import { applyEnvFile } from "../../scripts/lib/env.ts";
import {
  CLOUDFLARED_CONFIG,
  CLOUDFLARED_DIR,
  CURSOR_PUBLIC_BASE_URL,
  CURSOR_PUBLIC_HOST,
  ENV_FILE,
  LOCAL_BASE_URL,
  TUNNEL_NAME,
} from "../../scripts/lib/paths.ts";
import { askConfirm } from "../prompt.ts";
import { CommandError, type Command } from "../types.ts";

function log(msg: string): void {
  console.log(`[provision-tunnel] ${msg}`);
}

function resolveLocalService(): string {
  applyEnvFile(ENV_FILE);
  const fromEnv =
    process.env.BASE_URL?.trim() ||
    process.env.NEXT_PUBLIC_BASE_URL?.trim() ||
    LOCAL_BASE_URL;
  return fromEnv.replace(/\/$/, "");
}

function ensureTunnel(): string {
  const existing = listTunnels();
  const id = existing.get(TUNNEL_NAME);
  if (id) {
    log(`Tunnel "${TUNNEL_NAME}" already exists (${id})`);
    return id;
  }

  log(`Creating tunnel "${TUNNEL_NAME}"…`);
  const { status, stdout, stderr } = cloudflared([
    "tunnel",
    "create",
    TUNNEL_NAME,
  ]);
  if (status !== 0) {
    throw new CommandError(
      `cloudflared tunnel create failed:\n${stderr || stdout || `exit ${status}`}`,
    );
  }
  const combined = `${stdout}\n${stderr}`;
  const uuidMatch = combined.match(
    /([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/i,
  );
  if (uuidMatch?.[1]) {
    log(`Created tunnel ${uuidMatch[1]}`);
    return uuidMatch[1];
  }
  const after = listTunnels().get(TUNNEL_NAME);
  if (!after) {
    throw new CommandError(
      `Tunnel "${TUNNEL_NAME}" was created but could not resolve its UUID.\n${combined}`,
    );
  }
  return after;
}

function routeDns(): void {
  log(`Routing DNS ${CURSOR_PUBLIC_HOST} → tunnel ${TUNNEL_NAME}…`);
  const { status, stdout, stderr } = cloudflared([
    "tunnel",
    "route",
    "dns",
    "--overwrite-dns",
    TUNNEL_NAME,
    CURSOR_PUBLIC_HOST,
  ]);
  if (status !== 0) {
    const text = `${stderr}\n${stdout}`;
    if (/already exists|CNAME.*already/i.test(text) && /cfargotunnel/i.test(text)) {
      log("DNS route already in place");
      return;
    }
    throw new CommandError(
      `cloudflared tunnel route dns failed:\n${stderr || stdout || `exit ${status}`}`,
    );
  }
  if (stdout.trim()) console.log(stdout.trim());
  if (stderr.trim()) console.log(stderr.trim());
  log(`DNS OK: ${CURSOR_PUBLIC_HOST}`);
}

function writeConfig(tunnelId: string, service: string): void {
  const credentialsFile = credentialsPathForTunnel(tunnelId);
  mkdirSync(CLOUDFLARED_DIR, { mode: 0o700, recursive: true });
  const yaml = [
    `# Generated by 9router CLI provision-tunnel — do not commit`,
    `tunnel: ${tunnelId}`,
    `credentials-file: ${credentialsFile}`,
    `ingress:`,
    `  - hostname: ${CURSOR_PUBLIC_HOST}`,
    `    service: ${service}`,
    `  - service: http_status:404`,
    ``,
  ].join("\n");
  writeFileSync(CLOUDFLARED_CONFIG, yaml, { mode: 0o600 });
  log(`Wrote ${CLOUDFLARED_CONFIG}`);
  log(`credentials-file: ${credentialsFile}`);
}

export async function provisionTunnel(): Promise<void> {
  ensureCloudflared();
  ensureCloudflaredCert();

  const service = resolveLocalService();
  log(`Local service target: ${service}`);

  const tunnelId = ensureTunnel();
  routeDns();
  writeConfig(tunnelId, service);

  console.log("");
  console.log("OK — named tunnel provisioned.");
  console.log(`  Public URL: ${CURSOR_PUBLIC_BASE_URL}`);
  console.log("  Next: Daemons: Start, then Cursor: Sync.");
}

export async function foregroundTunnel(): Promise<void> {
  console.log(
    "Note: day-to-day use is Daemons: Start (app + tunnel together).",
  );
  console.log("This runs the tunnel in the foreground for debugging.");
  console.log("");

  const ok = await askConfirm(
    "Run foreground tunnel?",
    "Blocks this terminal until you stop it (Ctrl+C). Prefer Daemons: Start for normal use.",
    false,
  );
  if (!ok) {
    console.log("Cancelled.");
    return;
  }

  ensureCloudflared();

  if (!existsSync(CLOUDFLARED_CONFIG)) {
    throw new CommandError(
      [
        `Missing ${CLOUDFLARED_CONFIG}`,
        "Run Tunnel: Provision once first.",
        "(requires: brew install cloudflared && cloudflared tunnel login)",
      ].join("\n"),
    );
  }

  console.log(`[tunnel] Named tunnel → ${CURSOR_PUBLIC_HOST}`);
  console.log(`[tunnel] Config: ${CLOUDFLARED_CONFIG}`);
  console.log(`[tunnel] Cursor OpenAI base: ${CURSOR_PUBLIC_BASE_URL}/v1`);
  console.log("");

  await new Promise<void>((resolve, reject) => {
    const child = spawnCloudflared(
      ["tunnel", "--config", CLOUDFLARED_CONFIG, "run"],
      { stdio: "inherit" },
    );

    child.on("error", (err) => {
      reject(
        new CommandError(`Failed to start cloudflared: ${err.message}`),
      );
    });

    const shutdown = () => {
      child.kill("SIGTERM");
    };
    process.on("SIGINT", shutdown);
    process.on("SIGTERM", shutdown);

    child.on("exit", (code, signal) => {
      process.off("SIGINT", shutdown);
      process.off("SIGTERM", shutdown);
      if (signal) {
        console.log(`[tunnel] cloudflared exited on signal ${signal}`);
        resolve();
        return;
      }
      if (code && code !== 0) {
        reject(new CommandError(`cloudflared exited with code ${code}`));
        return;
      }
      resolve();
    });
  });
}

export const tunnelCommands: Command[] = [
  {
    id: "provision-tunnel",
    name: "Tunnel: Provision",
    description:
      "Create named Cloudflare tunnel + DNS for 9router.chrisvouga.dev",
    run: provisionTunnel,
  },
  {
    id: "tunnel",
    name: "Tunnel: Foreground",
    description: "Debug: run the named tunnel in the foreground",
    run: foregroundTunnel,
  },
];
