import { mkdirSync, writeFileSync } from "node:fs";
import { applyEnvFile } from "./lib/env.ts";
import {
  cloudflared,
  credentialsPathForTunnel,
  ensureCloudflared,
  ensureCloudflaredCert,
  listTunnels,
} from "./lib/cloudflared.ts";
import {
  CLOUDFLARED_CONFIG,
  CLOUDFLARED_DIR,
  CURSOR_PUBLIC_BASE_URL,
  CURSOR_PUBLIC_HOST,
  ENV_FILE,
  LOCAL_BASE_URL,
  TUNNEL_NAME,
} from "./lib/paths.ts";

function log(msg: string): void {
  console.log(`[provision-tunnel] ${msg}`);
}

function resolveLocalService(): string {
  applyEnvFile(ENV_FILE);
  const fromEnv =
    process.env.BASE_URL?.trim() ||
    process.env.NEXT_PUBLIC_BASE_URL?.trim() ||
    LOCAL_BASE_URL;
  return fromEnv.replace(/\/$/, "");
}

function ensureTunnel(): string {
  const existing = listTunnels();
  const id = existing.get(TUNNEL_NAME);
  if (id) {
    log(`Tunnel "${TUNNEL_NAME}" already exists (${id})`);
    return id;
  }

  log(`Creating tunnel "${TUNNEL_NAME}"…`);
  const { status, stdout, stderr } = cloudflared([
    "tunnel",
    "create",
    TUNNEL_NAME,
  ]);
  if (status !== 0) {
    throw new Error(
      `cloudflared tunnel create failed:\n${stderr || stdout || `exit ${status}`}`,
    );
  }
  const combined = `${stdout}\n${stderr}`;
  const uuidMatch = combined.match(
    /([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/i,
  );
  if (uuidMatch?.[1]) {
    log(`Created tunnel ${uuidMatch[1]}`);
    return uuidMatch[1];
  }
  // Fallback: re-list
  const after = listTunnels().get(TUNNEL_NAME);
  if (!after) {
    throw new Error(
      `Tunnel "${TUNNEL_NAME}" was created but could not resolve its UUID.\n${combined}`,
    );
  }
  return after;
}

function routeDns(): void {
  log(`Routing DNS ${CURSOR_PUBLIC_HOST} → tunnel ${TUNNEL_NAME}…`);
  const { status, stdout, stderr } = cloudflared([
    "tunnel",
    "route",
    "dns",
    "--overwrite-dns",
    TUNNEL_NAME,
    CURSOR_PUBLIC_HOST,
  ]);
  // overwrite may print success on stderr; non-zero only on hard failure
  if (status !== 0) {
    const text = `${stderr}\n${stdout}`;
    // Already correct CNAME is fine
    if (/already exists|CNAME.*already/i.test(text) && /cfargotunnel/i.test(text)) {
      log("DNS route already in place");
      return;
    }
    throw new Error(
      `cloudflared tunnel route dns failed:\n${stderr || stdout || `exit ${status}`}`,
    );
  }
  if (stdout.trim()) console.log(stdout.trim());
  if (stderr.trim()) console.log(stderr.trim());
  log(`DNS OK: ${CURSOR_PUBLIC_HOST}`);
}

function writeConfig(tunnelId: string, service: string): void {
  const credentialsFile = credentialsPathForTunnel(tunnelId);
  mkdirSync(CLOUDFLARED_DIR, { mode: 0o700, recursive: true });
  const yaml = [
    `# Generated by npm run provision-tunnel — do not commit`,
    `tunnel: ${tunnelId}`,
    `credentials-file: ${credentialsFile}`,
    `ingress:`,
    `  - hostname: ${CURSOR_PUBLIC_HOST}`,
    `    service: ${service}`,
    `  - service: http_status:404`,
    ``,
  ].join("\n");
  writeFileSync(CLOUDFLARED_CONFIG, yaml, { mode: 0o600 });
  log(`Wrote ${CLOUDFLARED_CONFIG}`);
  log(`credentials-file: ${credentialsFile}`);
}

function main(): void {
  ensureCloudflared();
  ensureCloudflaredCert();

  const service = resolveLocalService();
  log(`Local service target: ${service}`);

  const tunnelId = ensureTunnel();
  routeDns();
  writeConfig(tunnelId, service);

  console.log("");
  console.log("OK — named tunnel provisioned.");
  console.log(`  Public URL: ${CURSOR_PUBLIC_BASE_URL}`);
  console.log("  Next:");
  console.log("    npm run up       # terminal 1");
  console.log("    npm run tunnel   # terminal 2");
  console.log("    npm run sync-cursor");
  console.log("");
}

main();
