import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { loadEnvFile } from "./env.ts";

const here = dirname(fileURLToPath(import.meta.url));

/** Absolute path to the 9router/ package root. */
export const ROOT = resolve(here, "..", "..");

/** Infra repo root (parent of 9router/). */
export const REPO_ROOT = resolve(ROOT, "..");

export const APP_DIR = join(ROOT, "app");
export const DATA_DIR_DEFAULT = join(ROOT, "data");
export const ENV_FILE = join(ROOT, ".env");
export const ENV_EXAMPLE = join(ROOT, ".env.example");
export const PID_DIR = join(ROOT, ".pids");
export const APP_PID_FILE = join(PID_DIR, "9router.pid");
export const TUNNEL_PID_FILE = join(PID_DIR, "tunnel.pid");
export const APP_LOG_FILE = join(PID_DIR, "9router.log");
export const TUNNEL_LOG_FILE = join(PID_DIR, "tunnel.log");

export const SECRET_KEYS = [
  "JWT_SECRET",
  "INITIAL_PASSWORD",
  "API_KEY_SECRET",
  "MACHINE_ID_SALT",
] as const;

export type SecretKey = (typeof SECRET_KEYS)[number];

export const LOCAL_BASE_URL = "http://127.0.0.1:20128";

/** Stable public hostname for Cursor BYOK (named Cloudflare tunnel). */
export const CURSOR_PUBLIC_HOST = "9router.chrisvouga.dev";
export const CURSOR_PUBLIC_BASE_URL = `https://${CURSOR_PUBLIC_HOST}`;
export const TUNNEL_NAME = "9router";

/** Generated by CLI Provision tunnel; used by Start daemons / Foreground tunnel. */
export const CLOUDFLARED_DIR = join(ROOT, ".cloudflared");
export const CLOUDFLARED_CONFIG = join(CLOUDFLARED_DIR, "config.yml");
export const REPO_URL =
  process.env.NINEROUTER_REPO_URL?.trim() || "https://github.com/decolua/9router.git";
export const REPO_BRANCH = process.env.NINEROUTER_BRANCH?.trim() || "master";

/** Resolve DATA_DIR from env relative to ROOT when not absolute. */
export function resolveDataDir(raw?: string): string {
  const value = (raw ?? process.env.DATA_DIR ?? "./data").trim() || "./data";
  if (value.startsWith("/")) return value;
  return resolve(ROOT, value.replace(/^\.\//, ""));
}

/** DATA_DIR from project .env only — ignores ambient shell DATA_DIR. */
export function dataDirFromEnvFile(): string {
  const fileEnv = loadEnvFile(ENV_FILE);
  return resolveDataDir(fileEnv.DATA_DIR?.trim() || "./data");
}
