#!/usr/bin/env bash
# Remote deploy — invoked only from GitHub Actions CI via SSH.
set -euo pipefail

DEPLOY_DIR="${DEPLOY_DIR:-/opt/chrisvouga}"
SERVICE_ID="${1:-}"
IMAGE_TAG="${IMAGE_TAG:-latest}"

cd "${DEPLOY_DIR}"

is_infra_service() {
  local id="$1"
  awk -v id="$1" '
    /^infra_services:/ { in_infra=1; next }
    in_infra && /^[a-zA-Z_]/ { in_infra=0 }
    in_infra && /^  - id: / {
      line=$0
      sub(/^  - id: /, "", line)
      gsub(/ *$/, "", line)
      if (line == id) { found=1; exit }
    }
    END { exit(found ? 0 : 1) }
  ' services.yaml
}

compose_services() {
  docker compose config --services
}

deploy_all_services() {
  local pull_failed=()
  local svc

  echo "==> Pull all services (IMAGE_TAG=${IMAGE_TAG})"
  while IFS= read -r svc; do
    [[ -z "${svc}" ]] && continue
    echo "---- pull ${svc}"
    if ! docker compose pull "${svc}"; then
      pull_failed+=("${svc}")
      echo "WARN: pull failed for ${svc}" >&2
    fi
  done < <(compose_services)

  echo "==> Up all services"
  while IFS= read -r svc; do
    [[ -z "${svc}" ]] && continue
    if [[ " ${pull_failed[*]:-} " == *" ${svc} "* ]]; then
      echo "---- skip ${svc} (pull failed)"
      continue
    fi
    echo "---- up ${svc}"
    docker compose up -d "${svc}"
  done < <(compose_services)

  if [[ ${#pull_failed[@]} -gt 0 ]]; then
    echo "ERROR: failed to pull: ${pull_failed[*]}" >&2
    echo "       publish the image and ensure the ghcr package is public" >&2
    exit 1
  fi
}

if [[ -n "${SERVICE_ID}" ]]; then
  # docker compose service names match service ids (hyphens allowed)
  COMPOSE_SERVICE="${SERVICE_ID}"

  if [[ "${IMAGE_TAG}" != "latest" ]] && ! is_infra_service "${SERVICE_ID}"; then
    IMAGE="ghcr.io/crvouga/chrisvouga-${SERVICE_ID}:${IMAGE_TAG}"
    cat > docker-compose.override.yml <<EOF
# AUTO-GENERATED by scripts/deploy.sh — do not commit
services:
  ${COMPOSE_SERVICE}:
    image: ${IMAGE}
EOF
  else
    rm -f docker-compose.override.yml
  fi

  echo "==> Pull ${COMPOSE_SERVICE} (tag=${IMAGE_TAG})"
  docker compose pull "${COMPOSE_SERVICE}"
  echo "==> Up ${COMPOSE_SERVICE}"
  docker compose up -d "${COMPOSE_SERVICE}"
  docker compose logs --tail=40 "${COMPOSE_SERVICE}" 2>&1 || true
else
  rm -f docker-compose.override.yml
  export IMAGE_TAG
  deploy_all_services
fi

docker compose ps
