#!/usr/bin/env bash
# Remote deploy — invoked only from GitHub Actions CI via SSH.
set -euo pipefail

DEPLOY_DIR="${DEPLOY_DIR:-/opt/chrisvouga}"
SERVICE_ID="${1:-}"
IMAGE_TAG="${IMAGE_TAG:-latest}"

cd "${DEPLOY_DIR}"

if [[ -n "${SERVICE_ID}" ]]; then
  # docker compose service names match service ids (hyphens allowed)
  COMPOSE_SERVICE="${SERVICE_ID}"

  if [[ "${IMAGE_TAG}" != "latest" ]]; then
    IMAGE="ghcr.io/crvouga/chrisvouga-${SERVICE_ID}:${IMAGE_TAG}"
    cat > docker-compose.override.yml <<EOF
# AUTO-GENERATED by scripts/deploy.sh — do not commit
services:
  ${COMPOSE_SERVICE}:
    image: ${IMAGE}
EOF
  else
    rm -f docker-compose.override.yml
  fi

  echo "==> Pull ${COMPOSE_SERVICE} (tag=${IMAGE_TAG})"
  docker compose pull "${COMPOSE_SERVICE}"
  echo "==> Up ${COMPOSE_SERVICE}"
  docker compose up -d "${COMPOSE_SERVICE}"
else
  rm -f docker-compose.override.yml
  export IMAGE_TAG
  echo "==> Pull all services (IMAGE_TAG=${IMAGE_TAG})"
  docker compose pull
  echo "==> Up all services"
  docker compose up -d --remove-orphans
fi

docker compose ps
