#!/usr/bin/env bash
# Remote deploy — invoked only from GitHub Actions CI via SSH.
set -euo pipefail

DEPLOY_DIR="${DEPLOY_DIR:-/opt/chrisvouga}"
SERVICE_ID="${1:-}"
IMAGE_TAG="${IMAGE_TAG:-latest}"

cd "${DEPLOY_DIR}"

is_infra_service() {
  local id="$1"
  awk -v id="$1" '
    /^infra_services:/ { in_infra=1; next }
    in_infra && /^[a-zA-Z_]/ { in_infra=0 }
    in_infra && /^  - id: / {
      line=$0
      sub(/^  - id: /, "", line)
      gsub(/ *$/, "", line)
      if (line == id) { found=1; exit }
    }
    END { exit(found ? 0 : 1) }
  ' services.yaml
}

if [[ -n "${SERVICE_ID}" ]]; then
  # docker compose service names match service ids (hyphens allowed)
  COMPOSE_SERVICE="${SERVICE_ID}"

  if [[ "${IMAGE_TAG}" != "latest" ]] && ! is_infra_service "${SERVICE_ID}"; then
    IMAGE="ghcr.io/crvouga/chrisvouga-${SERVICE_ID}:${IMAGE_TAG}"
    cat > docker-compose.override.yml <<EOF
# AUTO-GENERATED by scripts/deploy.sh — do not commit
services:
  ${COMPOSE_SERVICE}:
    image: ${IMAGE}
EOF
  else
    rm -f docker-compose.override.yml
  fi

  echo "==> Pull ${COMPOSE_SERVICE} (tag=${IMAGE_TAG})"
  docker compose pull "${COMPOSE_SERVICE}"
  echo "==> Up ${COMPOSE_SERVICE}"
  docker compose up -d "${COMPOSE_SERVICE}"
  docker compose logs --tail=40 "${COMPOSE_SERVICE}" 2>&1 || true
else
  rm -f docker-compose.override.yml
  export IMAGE_TAG
  echo "==> Pull all services (IMAGE_TAG=${IMAGE_TAG})"
  docker compose pull
  echo "==> Up all services"
  docker compose up -d --remove-orphans
fi

docker compose ps
