#!/usr/bin/env bun
/**
 * Generate docker-compose.yml from services.yaml.
 *
 * Usage:
 *   bun run scripts/generate-compose.ts
 *   bun run scripts/generate-compose.ts --check   # exit 1 if out of date
 */
import { writeFileSync, readFileSync } from "node:fs";
import {
  composeServiceName,
  imageRepo,
  loadServicesConfig,
  type ServiceSpec,
  type ServicesConfig,
} from "../lib/services.js";

const HEADER = `# AUTO-GENERATED by scripts/generate-compose.ts — do not edit by hand.
# Regenerate: bun run generate-compose

`;

function traefikLabels(service: ServiceSpec): string {
  const name = composeServiceName(service.id);
  const router = name.replace(/-/g, "");
  return `    labels:
      - traefik.enable=true
      - traefik.http.routers.${router}.rule=Host(\`${service.hostname}\`)
      - traefik.http.routers.${router}.entrypoints=web
      - traefik.http.routers.${router}.middlewares=cfproto@docker
      - traefik.http.services.${router}.loadbalancer.server.port=${service.port}`;
}

function serviceBlock(
  service: ServiceSpec,
  config: ServicesConfig,
): string {
  const name = composeServiceName(service.id);
  const image = imageRepo(config, service.id);
  const envFile =
    service.secrets && service.secrets.length > 0
      ? `    env_file:\n      - ./env/${service.id}.env\n`
      : "";
  const envLines = service.env
    ? Object.entries(service.env)
        .map(([k, v]) => `      ${k}: "${v}"`)
        .join("\n")
    : "";
  const environment =
    envLines.length > 0 ? `    environment:\n${envLines}\n` : "";

  return `  ${name}:
    image: ${image}:\${IMAGE_TAG:-${config.default_image_tag}}
    restart: unless-stopped
    networks:
      - web
${envFile}${environment}${traefikLabels(service)}
`;
}

function generate(): string {
  const config = loadServicesConfig();
  const servicesYaml = config.services
    .map((s) => serviceBlock(s, config))
    .join("\n");

  return `${HEADER}name: chrisvouga

networks:
  web:
    name: chrisvouga-web

services:
  traefik:
    image: traefik:v3.6.6
    restart: unless-stopped
    command:
      - --configFile=/etc/traefik/traefik.yml
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.cfproto.headers.customrequestheaders.X-Forwarded-Proto=https

${servicesYaml}`;
}

const args = process.argv.slice(2);
const output = generate();

if (args.includes("--check")) {
  const existing = readFileSync("docker-compose.yml", "utf8");
  if (existing !== output) {
    console.error("docker-compose.yml is out of date — run: bun run generate-compose");
    process.exit(1);
  }
  console.log("docker-compose.yml is up to date");
  process.exit(0);
}

writeFileSync("docker-compose.yml", output);
console.log("Wrote docker-compose.yml");
