#!/usr/bin/env bun
/**
 * Generate fly/<id>/fly.toml from services.yaml.
 *
 * Usage:
 *   bun run scripts/generate-fly.ts
 *   bun run scripts/generate-fly.ts --check   # exit 1 if out of date
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  flyAppName,
  flyIsPublic,
  flyMinMachines,
  flyRegion,
  imageRepo,
  loadServicesConfig,
  type ServiceSpec,
  type ServicesConfig,
} from "../lib/services.js";

const HEADER = `# AUTO-GENERATED by scripts/generate-fly.ts — do not edit by hand.
# Regenerate: bun run generate-fly

`;

function vmMemory(service: ServiceSpec): string {
  if (service.id === "vault") return "512mb";
  if (service.id === "normalizer-worker") return "512mb";
  if (service.id === "normalizer") return "512mb";
  return "256mb";
}

function generateFlyToml(config: ServicesConfig, service: ServiceSpec, tag: string): string {
  const app = flyAppName(config, service.id);
  const region = flyRegion(config);
  const image = `${imageRepo(config, service.id)}:${tag}`;
  const minMachines = flyMinMachines(service);
  const lines: string[] = [
    `app = "${app}"`,
    `primary_region = "${region}"`,
    "",
    "[build]",
    `  image = "${image}"`,
    "",
    "[[vm]]",
    `  memory = "${vmMemory(service)}"`,
    '  cpu_kind = "shared"',
    "  cpus = 1",
  ];

  if (flyIsPublic(service) && service.port != null) {
    lines.push(
      "",
      "[http_service]",
      `  internal_port = ${service.port}`,
      "  force_https = true",
      '  auto_stop_machines = "stop"',
      "  auto_start_machines = true",
      `  min_machines_running = ${minMachines}`,
      "",
      "  [[http_service.checks]]",
      '    grace_period = "30s"',
      '    interval = "15s"',
      '    method = "GET"',
      `    path = "${service.health_path ?? "/"}"`,
      '    protocol = "http"',
      '    timeout = "5s"',
    );
  }

  if (!flyIsPublic(service) && flyMinMachines(service) > 0) {
    lines.push(
      "",
      "[[services]]",
      "  internal_port = 8080",
      '  protocol = "tcp"',
      '  auto_stop_machines = "off"',
      "  auto_start_machines = true",
      `  min_machines_running = ${minMachines}`,
      "",
      "  [[services.ports]]",
      "    port = 8080",
    );
  }

  return `${HEADER}${lines.join("\n")}\n`;
}

function parseArgs(argv: readonly string[]): { check: boolean; tag: string } {
  let check = false;
  let tag = loadServicesConfig().default_image_tag;
  for (const arg of argv) {
    if (arg === "--check") check = true;
    else if (arg === "--tag") {
      const idx = argv.indexOf(arg);
      tag = argv[idx + 1] ?? tag;
    } else if (arg === "--help" || arg === "-h") {
      console.log("Usage: bun run scripts/generate-fly.ts [--check] [--tag latest]");
      process.exit(0);
    }
  }
  return { check, tag };
}

function main(): void {
  const args = parseArgs(process.argv.slice(2));
  const config = loadServicesConfig();
  let drift = false;

  for (const service of config.services) {
    const dir = join("fly", service.id);
    const path = join(dir, "fly.toml");
    const content = generateFlyToml(config, service, args.tag);

    if (args.check) {
      let existing: string;
      try {
        existing = readFileSync(path, "utf8");
      } catch {
        console.error(`Missing ${path} — run: bun run generate-fly`);
        drift = true;
        continue;
      }
      if (existing !== content) {
        console.error(`Out of date: ${path} — run: bun run generate-fly`);
        drift = true;
      } else {
        console.log(`OK ${path}`);
      }
      continue;
    }

    mkdirSync(dir, { recursive: true });
    writeFileSync(path, content);
    console.log(`Wrote ${path}`);
  }

  if (args.check && drift) process.exit(1);
}

main();
