#!/usr/bin/env bun
/**
 * Generate docker-compose.yml from services.yaml.
 *
 * Usage:
 *   bun run scripts/generate-compose.ts
 *   bun run scripts/generate-compose.ts --check   # exit 1 if out of date
 */
import { writeFileSync, readFileSync } from "node:fs";
import {
  composeServiceName,
  imageRepo,
  isPublicService,
  loadServicesConfig,
  type InfraServiceSpec,
  type ServiceSpec,
  type ServicesConfig,
} from "../lib/services.js";

const HEADER = `# AUTO-GENERATED by scripts/generate-compose.ts — do not edit by hand.
# Regenerate: bun run generate-compose

`;

function routerName(id: string): string {
  return composeServiceName(id).replace(/-/g, "");
}

function traefikMiddlewares(extra?: readonly string[]): string {
  const chain = ["cfproto@docker", ...(extra ?? [])];
  return chain.join(",");
}

function traefikLabels(
  id: string,
  hostname: string,
  port: number,
  extraMiddlewares?: readonly string[],
): string {
  const router = routerName(id);
  return `    labels:
      - traefik.enable=true
      - traefik.http.routers.${router}.rule=Host(\`${hostname}\`)
      - traefik.http.routers.${router}.entrypoints=web
      - traefik.http.routers.${router}.middlewares=${traefikMiddlewares(extraMiddlewares)}
      - traefik.http.services.${router}.loadbalancer.server.port=${port}`;
}

function yamlList(items: readonly string[], indent: string): string {
  return items.map((item) => `${indent}- ${item}`).join("\n");
}

function serviceBlock(service: ServiceSpec, config: ServicesConfig): string {
  const name = composeServiceName(service.id);
  const image = imageRepo(config, service.id);
  const envFile =
    service.secrets && service.secrets.length > 0
      ? `    env_file:\n      - ./env/${service.id}.env\n`
      : "";
  const envLines = service.env
    ? Object.entries(service.env)
        .map(([k, v]) => `      ${k}: "${v}"`)
        .join("\n")
    : "";
  const environment =
    envLines.length > 0 ? `    environment:\n${envLines}\n` : "";
  const dependsOn =
    service.depends_on && service.depends_on.length > 0
      ? `    depends_on:\n${service.depends_on.map((d) => `      - ${composeServiceName(d)}`).join("\n")}\n`
      : "";
  const routing =
    isPublicService(service) && service.hostname && service.port != null
      ? traefikLabels(service.id, service.hostname, service.port)
      : "";

  return `  ${name}:
    image: ${image}:\${IMAGE_TAG:-${config.default_image_tag}}
    restart: unless-stopped
    networks:
      - web
${envFile}${environment}${dependsOn}${routing}`;
}

function infraServiceBlock(service: InfraServiceSpec): string {
  const name = composeServiceName(service.id);
  const envLines = service.env
    ? Object.entries(service.env)
        .map(([k, v]) => `      ${k}: "${v}"`)
        .join("\n")
    : "";
  const environment =
    envLines.length > 0 ? `    environment:\n${envLines}\n` : "";
  const volumes =
    service.volumes && service.volumes.length > 0
      ? `    volumes:\n${yamlList(service.volumes, "      ")}\n`
      : "";
  const capAdd =
    service.cap_add && service.cap_add.length > 0
      ? `    cap_add:\n${yamlList(service.cap_add, "      ")}\n`
      : "";
  const securityOpt =
    service.security_opt && service.security_opt.length > 0
      ? `    security_opt:\n${yamlList(service.security_opt, "      ")}\n`
      : "";
  const pid = service.pid ? `    pid: ${service.pid}\n` : "";
  const routing = traefikLabels(
    service.id,
    service.hostname,
    service.port,
    service.traefik_middlewares,
  );

  return `  ${name}:
    image: ${service.image}
    restart: unless-stopped
    networks:
      - web
${pid}${capAdd}${securityOpt}${volumes}${environment}${routing}`;
}

/** Named volume keys from infra bind specs like `netdataconfig:/etc/netdata`. */
function collectNamedVolumes(config: ServicesConfig): readonly string[] {
  const names = new Set<string>();
  for (const service of config.infra_services ?? []) {
    for (const vol of service.volumes ?? []) {
      const colon = vol.indexOf(":");
      if (colon <= 0) continue;
      const src = vol.slice(0, colon);
      if (!src.startsWith("/") && !src.startsWith(".")) {
        names.add(src);
      }
    }
  }
  return [...names].sort();
}

function volumesBlock(names: readonly string[]): string {
  if (names.length === 0) return "";
  const lines = names.map((n) => `  ${n}:`).join("\n");
  return `\nvolumes:\n${lines}\n`;
}

function generate(): string {
  const config = loadServicesConfig();
  const servicesYaml = config.services
    .map((s) => serviceBlock(s, config))
    .join("\n");
  const infraYaml = (config.infra_services ?? [])
    .map((s) => infraServiceBlock(s))
    .join("\n");
  const namedVolumes = volumesBlock(collectNamedVolumes(config));

  return `${HEADER}name: chrisvouga

networks:
  web:
    name: chrisvouga-web
${namedVolumes}
services:
  traefik:
    image: traefik:v3.6.6
    restart: unless-stopped
    command:
      - --configFile=/etc/traefik/traefik.yml
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic:/etc/traefik/dynamic:ro
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.cfproto.headers.customrequestheaders.X-Forwarded-Proto=https

${servicesYaml}
${infraYaml}`;
}

const args = process.argv.slice(2);
const output = generate();

if (args.includes("--check")) {
  const existing = readFileSync("docker-compose.yml", "utf8");
  if (existing !== output) {
    console.error("docker-compose.yml is out of date — run: bun run generate-compose");
    process.exit(1);
  }
  console.log("docker-compose.yml is up to date");
  process.exit(0);
}

writeFileSync("docker-compose.yml", output);
console.log("Wrote docker-compose.yml");
