#!/usr/bin/env bun
/**
 * Push publish-image.yml to every sibling repo listed in services.yaml.
 *
 * Usage:
 *   bun run rollout-publish
 *   bun run rollout-publish -- --dry-run
 *   bun run rollout-publish -- --repo crvouga/snake
 *   GITHUB_TOKEN_SUPER=... bun run rollout-publish -- --set-org-dispatch-secret
 */
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { $ } from "bun";
import { groupByGithubRepo, loadServicesConfig, type ServiceSpec } from "../lib/services.js";

type Args = {
  dryRun: boolean;
  repoFilter: string;
  setOrgDispatchSecret: boolean;
};

function parseArgs(argv: readonly string[]): Args {
  let dryRun = false;
  let repoFilter = "";
  let setOrgDispatchSecret = false;
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === "--dry-run") dryRun = true;
    else if (arg === "--repo") repoFilter = argv[++i] ?? "";
    else if (arg === "--set-org-dispatch-secret") setOrgDispatchSecret = true;
    else if (arg === "--help" || arg === "-h") {
      console.log(
        "Usage: bun run rollout-publish [--dry-run] [--repo owner/name] [--set-org-dispatch-secret]",
      );
      process.exit(0);
    } else {
      console.error(`Unknown argument: ${arg}`);
      process.exit(2);
    }
  }
  return { dryRun, repoFilter, setOrgDispatchSecret };
}

function jobName(service: ServiceSpec): string {
  return service.id.replace(/[^a-zA-Z0-9]/g, "_");
}

function renderPublishWorkflow(services: ServiceSpec[]): string {
  const jobs = services
    .map((s) => {
      const name = jobName(s);
      return `  ${name}:
    uses: crvouga/chrisvouga.dev/.github/workflows/reusable-publish-image.yml@main
    secrets:
      DEPLOY_DISPATCH_TOKEN: \${{ secrets.DEPLOY_DISPATCH_TOKEN }}
    with:
      service_id: ${s.id}
      dockerfile: ${s.dockerfile}
      context: ${s.build_context}`;
    })
    .join("\n\n");

  return `# AUTO-GENERATED by chrisvouga.dev/scripts/rollout-publish-workflows.ts — do not edit.
name: Publish image

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
${jobs}
`;
}

async function main(): Promise<void> {
  const args = parseArgs(process.argv.slice(2));
  const config = loadServicesConfig();
  const groups = groupByGithubRepo(config);

  const ghToken =
    process.env["GITHUB_TOKEN_SUPER"]?.trim() ||
    process.env["GH_TOKEN"]?.trim() ||
    process.env["GITHUB_TOKEN"]?.trim();

  if (args.setOrgDispatchSecret) {
    if (!ghToken) throw new Error("GITHUB_TOKEN_SUPER required for --set-org-dispatch-secret");
    if (args.dryRun) {
      console.log("[dry-run] Would set org secret DEPLOY_DISPATCH_TOKEN");
    } else {
      process.env["GH_TOKEN"] = ghToken;
      await $`gh secret set DEPLOY_DISPATCH_TOKEN --org crvouga --body ${ghToken}`.quiet();
      console.log("Set org secret DEPLOY_DISPATCH_TOKEN");
    }
  }

  const workRoot = mkdtempSync(join(tmpdir(), "chrisvouga-rollout-"));

  try {
    for (const [repo, services] of groups) {
      if (args.repoFilter && repo !== args.repoFilter) continue;

      const workflow = renderPublishWorkflow(services);
      const relPath = ".github/workflows/publish-image.yml";

      console.log(`\n${repo} (${services.length} service(s))`);
      if (args.dryRun) {
        console.log("--- publish-image.yml ---");
        console.log(workflow);
        continue;
      }

      if (!ghToken) {
        throw new Error("GITHUB_TOKEN_SUPER or GH_TOKEN required for push");
      }

      const cloneDir = join(workRoot, repo.replace("/", "__"));
      process.env["GH_TOKEN"] = ghToken;
      await $`gh repo clone ${repo} ${cloneDir} -- --depth 1`.quiet();

      const workflowPath = join(cloneDir, relPath);
      mkdirSync(join(cloneDir, ".github/workflows"), { recursive: true });

      const existing = existsSync(workflowPath)
        ? readFileSync(workflowPath, "utf8")
        : null;
      if (existing === workflow) {
        console.log("  unchanged — skip");
        continue;
      }

      writeFileSync(workflowPath, workflow);
      await $`git -C ${cloneDir} add ${relPath}`.quiet();
      await $`git -C ${cloneDir} commit -m ${"ci: add publish-image workflow for chrisvouga.dev deploy"}`.quiet()
        .nothrow();
      const push = await $`git -C ${cloneDir} push origin main`.quiet().nothrow();
      if (push.exitCode !== 0) {
        throw new Error(`git push failed for ${repo}: ${push.stderr.toString()}`);
      }
      console.log("  pushed to main");
    }
  } finally {
    rmSync(workRoot, { recursive: true, force: true });
  }

  console.log("\nRollout complete");
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
});
